@startuml Deployer State Machine

hide empty description

[*] -right-> Power_On

Power_On -up-> Telemetry_Transmission : Begin Transmitting Telemetry

State Telemetry_Transmission {
    Record_IMU_Data --> Transmit_IMU_Packet
    Transmit_IMU_Packet --> Ping_PicoSat1
    Ping_PicoSat1 --> Ping_PicoSat2
    Ping_PicoSat2 --> Ping_PicoSat3
    Ping_PicoSat3 --> Ping_PicoSat4
    Ping_PicoSat4 --> Record_IMU_Data
}

Power_On -right-> Idle
Idle -down-> Deploy_Counterweight : 14ft Clearence Zone Left
Deploy_Counterweight -down-> Spin_Up_One

Spin_Up_One -down-> Deployment_Ready_One : RPM Reached

State Spin_Up_Attempts {
    Engage : Engage Motor PID
    Engage -right-> Fail : RPM not reached
    Fail --> Engage : Attempts < 3
    Fail --> Adjust : Attempts > 3
    Adjust --> Engage : Lower RPM Target
}

Deployment_Ready_One --> Symetric_Deployment : Deployment Window
Symetric_Deployment -down-> Spin_Up_Two

Spin_Up_Two -down-> Deployment_Ready_Two : RPM Reached

Deployment_Ready_Two --> Asymetric_Deployment : Deployment Window

Asymetric_Deployment -down-> Wait_For_Power_Off
Wait_For_Power_Off -down-> [*]

@enduml