@startuml Ejector State Machine

Idle : Wait for JUPITER

hide empty description

[*] -right-> Power_On
Power_On -right-> Idle
Idle -right-> Eject : Ejection Signal High
Eject --> Record

State Record {
    State Pass_Back : Send data to JUPITER
    Wait --> Packet : Packer Received
    Packet --> Pass_Back : Packet Decoded
    Pass_Back --> Wait
}

Record -left-> [*] : Power Loss

@enduml