@startuml Jupiter State Machine

hide empty description

Launch : Determine T=0
EXP_Trigger : Trigger Experiment
Battery_Activation : Triggers Battery Latch

[*] -right-> PowerOn
PowerOn -right-> Launch
Launch -right-> Spindown : Acceleration Stopped
Spindown -right-> EXP_Trigger : Spindown Complete
EXP_Trigger -down-> Battery_Activation
Battery_Activation -left-> Experiment_Running

state Experiment_Running {
    Receive_Data --> Record_Data
    Record_Data --> Receive_Data
}

Experiment_Running -left-> Battery_Shutdown : T+600 Seconds
Battery_Shutdown -left-> [*]

@enduml