@startuml  TERMINUS-PICO library

!include Arduino.puml

package "TERMINUS-PICO" {
    Class HC12 {
        - SerialPIO HC12_Serial
        + bool begin()
        + bool program()
        + void send(char c)
        + void sendString(String s)
        + char read()
        + bool available()
        + String readString()
    }

    Class R_L_Servo {
        - int pin
        - Servo servo
        + void RL_Servo(int pin)
        + void begin()
        + void set(int angle)
    }

    Class RBF {
        - int pin
        + RBF(int pin)
        + bool isPulled()
    }

    SerialPIO --* HC12
}

hide empty members

@enduml